### ISSUE TITLE
API Doc Navigation Improvement

### ISSUE THREAD

**Issue by torbensky** [saasquatch/saasquatch-docs#20]
Right now, you click on a documentation link in the left side navbar and it takes you down there with no obvious navigation elements to take you back or somewhere else. My initial reaction is that I have to scroll. I eventually discovered that we have proper back button support so I could just use that. I don't think that is very intuitive given how spottily back button support is implemented across sites. Furthermore, I just feel a bit lost when I want to explore the documentation. I think having navigation structure continue to follow (why not, we aren't using the space?) it would feel a bit less like you are jumping into the middle of a giant document.

**Comment by loganvolkers** [comment]
Ready to deploy, blocked by #67
