### ISSUE TITLE
Add "View on GitHub" links on pages?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [saasquatch/saasquatch-docs#81]
It's a bit cumbersome to match up online docs to their corresponding pages. For example, what does https://docs.referralsaasquatch.com/developer/squatchjs/v2/ match to?

If a little button on the bottom of each page with a link to the backing `.md` file were added, that'd be really useful!

**Comment by loganvolkers** [comment]
Thanks for the suggestion Josh, we used to have this, but now we are migrating more and more of our content out of this repo into other sources like Contentful. Love the idea, but in reality we have received few contributions (besides yours of course thanks!)
